function NeuMotorsproductmatrix = importNMproductMatrix(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  NEUMOTORSPRODUCTMATRIX = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  NEUMOTORSPRODUCTMATRIX = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  NEUMOTORSPRODUCTMATRIX = IMPORTFILE(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NeuMotorsproductmatrix = importfile("C:\Users\cmmcguir\OneDrive - North Carolina State University\iSSRL\Research\variable-stiffness-WEC\wecSim_projects\ONR\p3_1m\NeuMotors_product_matrix.xlsx", "3805", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Aug-2025 15:17:11

%% Input handling

% If no sheet is specified, read from 3805
if nargin == 1 || isempty(sheetName)
    sheetName = "3805";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [4, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":H" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["Motor", "RPMs", "RmOhms", "Io", "Torque", "Torque1", "MaxVolts", "MaxAmps"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Motor", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Motor", "EmptyFieldRule", "auto");

% Import the data
NeuMotorsproductmatrix = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":H" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    NeuMotorsproductmatrix = [NeuMotorsproductmatrix; tb]; %#ok<AGROW>
end

end